import { z } from 'zod';
import { LOCALES, MODULE_NAMES, SECTIONS, THEMES } from '@/src/lib/config';
import { SiteContentSchema } from '@/src/lib/content';

/**
 * The questionnaire answers that `yarn client:init` turns into a client site.
 * The /new-client skill (and the agency order pipeline) produce this JSON.
 * Only `slug`, `business.name` and `theme` are required; everything else has
 * sensible defaults, and missing website copy is filled from the theme's demo.
 */
const Localized = z.object({
  'zh-Hant': z.string().optional(),
  'zh-Hans': z.string().optional(),
  en: z.string().optional(),
});

export const AnswersSchema = z.object({
  slug: z
    .string()
    .regex(/^[a-z0-9]+(-[a-z0-9]+)*$/, { message: 'Use lowercase letters, numbers and dashes (e.g. "harmony-move")' })
    .max(40),
  business: z.object({
    name: Localized.refine((n) => Object.values(n).some(Boolean), { message: 'Business name is required' }),
    phone: z.string().default(''),
    whatsapp: z.string().default(''),
    email: z.string().default(''),
    address: Localized.default({}),
  }),
  locales: z.array(z.enum(LOCALES)).min(1).default(['zh-Hant', 'en']),
  theme: z.enum(THEMES),
  modules: z.array(z.enum(MODULE_NAMES)).default([]),
  sections: z.array(z.enum(SECTIONS)).min(1).default(['hero', 'services', 'cases', 'about', 'contact']),
  notifyEmails: z.array(z.string().email()).default([]),
  timezone: z.string().default('Asia/Hong_Kong'),
  currency: z.string().length(3).default('HKD'),
  /** Optional copy per locale; missing locales are copied from the theme demo. */
  content: z.object({ 'zh-Hant': SiteContentSchema.optional(), 'zh-Hans': SiteContentSchema.optional(), en: SiteContentSchema.optional() }).default({}),
  owner: z.object({ name: z.string().min(2), email: z.string().email() }).optional(),
  domain: z.string().optional(),
});

export type Answers = z.infer<typeof AnswersSchema>;
export type AnswersInput = z.input<typeof AnswersSchema>;

/** Required environment variables for each optional module. */
export const MODULE_ENV: Record<string, string[]> = {
  core: ['MONGODB_URI', 'MONGODB_DB', 'JWT_ADMIN_SECRET', 'NEXT_PUBLIC_SITE_URL'],
  email: ['SMTP_HOST', 'SMTP_PORT', 'SMTP_USER', 'SMTP_PASS', 'SMTP_FROM'],
  stripe: ['STRIPE_SECRET_KEY', 'STRIPE_WEBHOOK_SECRET'],
  gcal: ['GOOGLE_SERVICE_ACCOUNT_JSON', 'GOOGLE_CALENDAR_ID'],
};

/** Renders client.config.ts source from answers. */
export function renderClientConfig(a: Answers): string {
  const mods = Object.fromEntries(MODULE_NAMES.map((m) => [m, a.modules.includes(m)]));
  const cfg = {
    business: { ...a.business, logo: '/logo.svg' },
    locales: a.locales,
    theme: a.theme,
    modules: mods,
    sections: a.sections,
    notify: { email: a.notifyEmails },
    timezone: a.timezone,
    currency: a.currency,
  };
  return `import { defineClientConfig } from './src/lib/config';

/**
 * The ONE file to edit per client (generated by \`yarn client:init\`).
 * Validated at startup by \`src/lib/config.ts\`; \`yarn client:check\` checks it too.
 */
export default defineClientConfig(${JSON.stringify(cfg, null, 2)});
`;
}
