import { defineClientConfig } from './src/lib/config';

/**
 * The ONE file to edit per client (generated by `yarn client:init`).
 * Validated at startup by `src/lib/config.ts`; `yarn client:check` checks it too.
 */
export default defineClientConfig({
  "business": {
    "name": {
      "zh-Hant": "DenEx AI Websites",
      "zh-Hans": "DenEx AI Websites",
      "en": "DenEx AI Websites"
    },
    "phone": "",
    "whatsapp": "",
    "email": "",
    "address": {
      "zh-Hant": "香港",
      "en": "Hong Kong"
    },
    "logo": "/denex-logo.png"
  },
  "locales": [
    "zh-Hant",
    "en"
  ],
  "theme": "corporate",
  "modules": {
    "booking": true,
    "payments": true,
    "stripe": true,
    "gcal": false,
    "catalog": false,
    "mobile": false
  },
  "sections": [
    "hero",
    "services",
    "cases",
    "about",
    "contact"
  ],
  "notify": {
    "email": []
  },
  "timezone": "Asia/Hong_Kong",
  "currency": "HKD"
});
