// Turns questionnaire answers into this client's site:
//   yarn client:init --answers answers.json
// Writes client.config.ts, content/<locale>.json (demo copy for missing locales),
// and .env.local with fresh secrets (only if .env.local does not exist yet).
import { existsSync } from 'node:fs';
import { readFile, writeFile } from 'node:fs/promises';
import { randomBytes } from 'node:crypto';
import path from 'node:path';
import { AnswersSchema, renderClientConfig } from '@/src/lib/answers';
import { LOCALES, parseClientConfig } from '@/src/lib/config';
import { DemoDataSchema } from '@/src/lib/demo';

const root = path.resolve(__dirname, '..');
const argi = process.argv.indexOf('--answers');
const file = argi >= 0 ? process.argv[argi + 1] : undefined;
if (!file) {
  console.error('Usage: yarn client:init --answers answers.json');
  process.exit(1);
}

async function main(answersPath: string) {
  const raw = JSON.parse(await readFile(path.resolve(answersPath), 'utf8'));
  const parsed = AnswersSchema.safeParse(raw);
  if (!parsed.success) {
    console.error('answers.json is invalid:');
    for (const i of parsed.error.issues) console.error(`  - ${i.path.join('.')}: ${i.message}`);
    process.exit(1);
  }
  const a = parsed.data;

  const source = renderClientConfig(a);
  // Validate exactly what we are about to write (module deps, default-locale name, …).
  const cfgObject = JSON.parse(source.slice(source.indexOf('defineClientConfig(') + 'defineClientConfig('.length, source.lastIndexOf(');')));
  parseClientConfig(cfgObject);
  await writeFile(path.join(root, 'client.config.ts'), source);
  console.log('✓ client.config.ts');

  const demo = DemoDataSchema.parse(JSON.parse(await readFile(path.join(root, 'demo', `${a.theme}.json`), 'utf8')));
  for (const locale of LOCALES) {
    const content = a.content[locale] ?? demo.content[locale];
    await writeFile(path.join(root, 'content', `${locale}.json`), JSON.stringify(content, null, 2) + '\n');
    console.log(`✓ content/${locale}.json${a.content[locale] ? '' : ' (demo copy — replace with the client’s text)'}`);
  }

  const envPath = path.join(root, '.env.local');
  if (existsSync(envPath)) {
    console.log('• .env.local already exists — left unchanged');
  } else {
    const secret = () => randomBytes(32).toString('hex');
    const env = [
      '# Generated by yarn client:init — fill in the blanks, never commit this file.',
      `MONGODB_URI=`,
      `MONGODB_DB=${a.slug.replace(/-/g, '_')}`,
      `JWT_SECRET=${secret()}`,
      `JWT_ADMIN_SECRET=${secret()}`,
      `NEXT_PUBLIC_SITE_URL=${a.domain ? `https://${a.domain}` : 'http://localhost:3000'}`,
      'DEFAULT_ADMIN=true',
      'SMTP_HOST=',
      'SMTP_PORT=587',
      'SMTP_USER=',
      'SMTP_PASS=',
      `SMTP_FROM=`,
      ...(a.modules.includes('stripe') ? ['STRIPE_SECRET_KEY=', 'STRIPE_WEBHOOK_SECRET='] : []),
      ...(a.modules.includes('gcal') ? ['GOOGLE_SERVICE_ACCOUNT_JSON=', 'GOOGLE_CALENDAR_ID='] : []),
    ].join('\n');
    await writeFile(envPath, env + '\n');
    console.log('✓ .env.local (fresh JWT secrets)');
  }

  if (a.owner) {
    await writeFile(path.join(root, '.owner.json'), JSON.stringify(a.owner, null, 2) + '\n');
    console.log(`✓ owner recorded (${a.owner.email}) — create the login with: yarn admin:create --email ${a.owner.email} --name "${a.owner.name}"`);
  }
  console.log(`\nDone: ${a.slug} · theme ${a.theme} · modules [${a.modules.join(', ') || 'core only'}]`);
}

main(file).catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
